import { Component } from '@angular/core';
import { IonHeader, IonToolbar, IonTitle, IonContent } from '@ionic/angular';
import { Pelicula } from '../interfaces/pelicula';
import { PeliculaItemComponent } from '../components/pelicula-item/pelicula-item.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  imports: [IonHeader, IonToolbar, IonTitle, IonContent, PeliculaItemComponent, CommonModule],
})
export class HomePage {

  listaDePeliculas: Pelicula[] = [
    { id: 1, titulo: "Interestelar", director: "Christopher Nolan", año: 2014, genero: "Ciencia ficción", alquilada: false },
    { id: 2, titulo: "El Padrino", director: "Francis Ford Coppola", año: 1972, genero: "Drama", alquilada: true },
    { id: 3, titulo: "Jurassic Park", director: "Steven Spielberg", año: 1993, genero: "Aventura", alquilada: false },
    { id: 4, titulo: "Titanic", director: "James Cameron", año: 1997, genero: "Romance", alquilada: true },
    { id: 5, titulo: "Matrix", director: "Lana Wachowski, Lilly Wachowski", año: 1999, genero: "Ciencia ficción", alquilada: false },
    { id: 6, titulo: "El Señor de los Anillos: La Comunidad del Anillo", director: "Peter Jackson", año: 2001, genero: "Fantasía", alquilada: false },
    { id: 7, titulo: "El Señor de los Anillos: Las Dos Torres", director: "Peter Jackson", año: 2002, genero: "Fantasía", alquilada: true },
    { id: 8, titulo: "El Señor de los Anillos: El Retorno del Rey", director: "Peter Jackson", año: 2003, genero: "Fantasía", alquilada: false },
    { id: 9, titulo: "Harry Potter y la Piedra Filosofal", director: "Chris Columbus", año: 2001, genero: "Fantasía", alquilada: true },
    { id: 10, titulo: "Harry Potter y la Cámara Secreta", director: "Chris Columbus", año: 2002, genero: "Fantasía", alquilada: false },

    { id: 11, titulo: "Harry Potter y el Prisionero de Azkaban", director: "Alfonso Cuarón", año: 2004, genero: "Fantasía", alquilada: false },
    { id: 12, titulo: "Harry Potter y el Cáliz de Fuego", director: "Mike Newell", año: 2005, genero: "Fantasía", alquilada: true },
    { id: 13, titulo: "Harry Potter y la Orden del Fénix", director: "David Yates", año: 2007, genero: "Fantasía", alquilada: false },
    { id: 14, titulo: "Harry Potter y el Misterio del Príncipe", director: "David Yates", año: 2009, genero: "Fantasía", alquilada: true },
    { id: 15, titulo: "Harry Potter y las Reliquias de la Muerte", director: "David Yates", año: 2010, genero: "Fantasía", alquilada: false },
    { id: 16, titulo: "Avatar", director: "James Cameron", año: 2009, genero: "Ciencia ficción", alquilada: true },
    { id: 17, titulo: "Avatar: El sentido del agua", director: "James Cameron", año: 2022, genero: "Ciencia ficción", alquilada: false },
    { id: 18, titulo: "Vengadores: Endgame", director: "Anthony Russo, Joe Russo", año: 2019, genero: "Acción", alquilada: true },
    { id: 19, titulo: "Vengadores: Infinity War", director: "Anthony Russo, Joe Russo", año: 2018, genero: "Acción", alquilada: false },
    { id: 20, titulo: "Iron Man", director: "Jon Favreau", año: 2008, genero: "Acción", alquilada: false },

    { id: 21, titulo: "Spider-Man", director: "Sam Raimi", año: 2002, genero: "Acción", alquilada: true },
    { id: 22, titulo: "Spider-Man 2", director: "Sam Raimi", año: 2004, genero: "Acción", alquilada: false },
    { id: 23, titulo: "Spider-Man: No Way Home", director: "Jon Watts", año: 2021, genero: "Acción", alquilada: true },
    { id: 24, titulo: "Batman Begins", director: "Christopher Nolan", año: 2005, genero: "Acción", alquilada: false },
    { id: 25, titulo: "The Dark Knight", director: "Christopher Nolan", año: 2008, genero: "Acción", alquilada: false },
    { id: 26, titulo: "Joker", director: "Todd Phillips", año: 2019, genero: "Drama", alquilada: true },
    { id: 27, titulo: "Gladiator", director: "Ridley Scott", año: 2000, genero: "Acción", alquilada: false },
    { id: 28, titulo: "Troya", director: "Wolfgang Petersen", año: 2004, genero: "Acción", alquilada: true },
    { id: 29, titulo: "300", director: "Zack Snyder", año: 2006, genero: "Acción", alquilada: false },
    { id: 30, titulo: "Piratas del Caribe: La maldición de la Perla Negra", director: "Gore Verbinski", año: 2003, genero: "Aventura", alquilada: true },

    { id: 31, titulo: "Piratas del Caribe: El cofre del hombre muerto", director: "Gore Verbinski", año: 2006, genero: "Aventura", alquilada: false },
    { id: 32, titulo: "Indiana Jones y el templo maldito", director: "Steven Spielberg", año: 1984, genero: "Aventura", alquilada: true },
    { id: 33, titulo: "Indiana Jones y la última cruzada", director: "Steven Spielberg", año: 1989, genero: "Aventura", alquilada: false },
    { id: 34, titulo: "Regreso al Futuro", director: "Robert Zemeckis", año: 1985, genero: "Ciencia ficción", alquilada: false },
    { id: 35, titulo: "Regreso al Futuro II", director: "Robert Zemeckis", año: 1989, genero: "Ciencia ficción", alquilada: true },
    { id: 36, titulo: "Regreso al Futuro III", director: "Robert Zemeckis", año: 1990, genero: "Ciencia ficción", alquilada: false },
    { id: 37, titulo: "Forrest Gump", director: "Robert Zemeckis", año: 1994, genero: "Drama", alquilada: true },
    { id: 38, titulo: "Cadena perpetua", director: "Frank Darabont", año: 1994, genero: "Drama", alquilada: false },
    { id: 39, titulo: "La vida es bella", director: "Roberto Benigni", año: 1997, genero: "Drama", alquilada: false },
    { id: 40, titulo: "Salvar al soldado Ryan", director: "Steven Spielberg", año: 1998, genero: "Bélica", alquilada: true },

    { id: 41, titulo: "La lista de Schindler", director: "Steven Spielberg", año: 1993, genero: "Drama", alquilada: false },
    { id: 42, titulo: "Braveheart", director: "Mel Gibson", año: 1995, genero: "Drama", alquilada: true },
    { id: 43, titulo: "El gran dictador", director: "Charles Chaplin", año: 1940, genero: "Comedia", alquilada: false },
    { id: 44, titulo: "Tiempos modernos", director: "Charles Chaplin", año: 1936, genero: "Comedia", alquilada: false },
    { id: 45, titulo: "Psicosis", director: "Alfred Hitchcock", año: 1960, genero: "Terror", alquilada: true },
    { id: 46, titulo: "El resplandor", director: "Stanley Kubrick", año: 1980, genero: "Terror", alquilada: false },
    { id: 47, titulo: "It", director: "Andy Muschietti", año: 2017, genero: "Terror", alquilada: true },
    { id: 48, titulo: "Scream", director: "Wes Craven", año: 1996, genero: "Terror", alquilada: false },
    { id: 49, titulo: "Alien, el octavo pasajero", director: "Ridley Scott", año: 1979, genero: "Terror", alquilada: true },
    { id: 50, titulo: "Terminator", director: "James Cameron", año: 1984, genero: "Ciencia ficción", alquilada: false },

    { id: 51, titulo: "Terminator 2: El juicio final", director: "James Cameron", año: 1991, genero: "Ciencia ficción", alquilada: true },
    { id: 52, titulo: "Blade Runner", director: "Ridley Scott", año: 1982, genero: "Ciencia ficción", alquilada: false },
    { id: 53, titulo: "Dune", director: "Denis Villeneuve", año: 2021, genero: "Ciencia ficción", alquilada: false },
    { id: 54, titulo: "Dune: Parte Dos", director: "Denis Villeneuve", año: 2024, genero: "Ciencia ficción", alquilada: true },
    { id: 55, titulo: "Mad Max: Fury Road", director: "George Miller", año: 2015, genero: "Acción", alquilada: false },
    { id: 56, titulo: "Top Gun", director: "Tony Scott", año: 1986, genero: "Acción", alquilada: true },
    { id: 57, titulo: "Top Gun: Maverick", director: "Joseph Kosinski", año: 2022, genero: "Acción", alquilada: false },
    { id: 58, titulo: "Rocky", director: "John G. Avildsen", año: 1976, genero: "Drama", alquilada: false },
    { id: 59, titulo: "Rocky II", director: "Sylvester Stallone", año: 1979, genero: "Drama", alquilada: true },
    { id: 60, titulo: "Creed", director: "Ryan Coogler", año: 2015, genero: "Drama", alquilada: false },

    { id: 61, titulo: "Toy Story", director: "John Lasseter", año: 1995, genero: "Animación", alquilada: true },
    { id: 62, titulo: "Toy Story 2", director: "John Lasseter", año: 1999, genero: "Animación", alquilada: false },
    { id: 63, titulo: "Toy Story 3", director: "Lee Unkrich", año: 2010, genero: "Animación", alquilada: false },
    { id: 64, titulo: "Buscando a Nemo", director: "Andrew Stanton", año: 2003, genero: "Animación", alquilada: true },
    { id: 65, titulo: "Los Increíbles", director: "Brad Bird", año: 2004, genero: "Animación", alquilada: false },
    { id: 66, titulo: "Up", director: "Pete Docter", año: 2009, genero: "Animación", alquilada: true },
    { id: 67, titulo: "Wall-E", director: "Andrew Stanton", año: 2008, genero: "Animación", alquilada: false },
    { id: 68, titulo: "Coco", director: "Lee Unkrich", año: 2017, genero: "Animación", alquilada: false },
    { id: 69, titulo: "Shrek", director: "Andrew Adamson", año: 2001, genero: "Animación", alquilada: true },
    { id: 70, titulo: "El Rey León", director: "Roger Allers, Rob Minkoff", año: 1994, genero: "Animación", alquilada: false },

    { id: 71, titulo: "Frozen", director: "Chris Buck, Jennifer Lee", año: 2013, genero: "Animación", alquilada: true },
    { id: 72, titulo: "Vaiana", director: "Ron Clements, John Musker", año: 2016, genero: "Animación", alquilada: false },
    { id: 73, titulo: "Aladdin", director: "Ron Clements, John Musker", año: 1992, genero: "Animación", alquilada: false },
    { id: 74, titulo: "Mulan", director: "Tony Bancroft, Barry Cook", año: 1998, genero: "Animación", alquilada: true },
    { id: 75, titulo: "La Bella y la Bestia", director: "Gary Trousdale, Kirk Wise", año: 1991, genero: "Animación", alquilada: false },
    { id: 76, titulo: "Pretty Woman", director: "Garry Marshall", año: 1990, genero: "Romance", alquilada: true },
    { id: 77, titulo: "Grease", director: "Randal Kleiser", año: 1978, genero: "Musical", alquilada: false },
    { id: 78, titulo: "La La Land", director: "Damien Chazelle", año: 2016, genero: "Musical", alquilada: true },
    { id: 79, titulo: "Mamma Mia!", director: "Phyllida Lloyd", año: 2008, genero: "Musical", alquilada: false },
    { id: 80, titulo: "Bohemian Rhapsody", director: "Bryan Singer", año: 2018, genero: "Musical", alquilada: true },

    { id: 81, titulo: "El silencio de los corderos", director: "Jonathan Demme", año: 1991, genero: "Thriller", alquilada: false },
    { id: 82, titulo: "Seven", director: "David Fincher", año: 1995, genero: "Thriller", alquilada: true },
    { id: 83, titulo: "Origen", director: "Christopher Nolan", año: 2010, genero: "Ciencia ficción", alquilada: false },
    { id: 84, titulo: "Memento", director: "Christopher Nolan", año: 2000, genero: "Thriller", alquilada: true },
    { id: 85, titulo: "Pulp Fiction", director: "Quentin Tarantino", año: 1994, genero: "Crimen", alquilada: false },
    { id: 86, titulo: "Kill Bill", director: "Quentin Tarantino", año: 2003, genero: "Acción", alquilada: true },
    { id: 87, titulo: "Django desencadenado", director: "Quentin Tarantino", año: 2012, genero: "Western", alquilada: false },
    { id: 88, titulo: "Érase una vez en Hollywood", director: "Quentin Tarantino", año: 2019, genero: "Comedia", alquilada: false },
    { id: 89, titulo: "El bueno, el feo y el malo", director: "Sergio Leone", año: 1966, genero: "Western", alquilada: true },
    { id: 90, titulo: "Sin perdón", director: "Clint Eastwood", año: 1992, genero: "Western", alquilada: false },

    { id: 91, titulo: "Oppenheimer", director: "Christopher Nolan", año: 2023, genero: "Drama", alquilada: true },
    { id: 92, titulo: "Barbie", director: "Greta Gerwig", año: 2023, genero: "Comedia", alquilada: false },
    { id: 93, titulo: "Parásitos", director: "Bong Joon-ho", año: 2019, genero: "Drama", alquilada: true },
    { id: 94, titulo: "Jumanji", director: "Joe Johnston", año: 1995, genero: "Aventura", alquilada: false },
    { id: 95, titulo: "Zootrópolis", director: "Byron Howard, Rich Moore", año: 2016, genero: "Animación", alquilada: true },
    { id: 96, titulo: "Piratas del Caribe: En el fin del mundo", director: "Gore Verbinski", año: 2007, genero: "Aventura", alquilada: false },
    { id: 97, titulo: "Los juegos del hambre", director: "Gary Ross", año: 2012, genero: "Ciencia ficción", alquilada: true },
    { id: 98, titulo: "Crepúsculo", director: "Catherine Hardwicke", año: 2008, genero: "Romance", alquilada: false },
    { id: 99, titulo: "Los Vengadores", director: "Joss Whedon", año: 2012, genero: "Acción", alquilada: true },
    { id: 100, titulo: "Star Wars: Una nueva esperanza", director: "George Lucas", año: 1977, genero: "Ciencia ficción", alquilada: false }
];
  constructor() {}
}
